const loginErrors = {
  INCOMPLETE_LOGIN_CREDENTIALS: "LG-1000",
  INVALID_EMAIL_PATTERN: "LG-1001",
  INCORRECT_PASSWORD: "LG-1002",
  USER_DOES_NOT_EXIST: "LG-1003",
  USER_INACTIVE: "LG-1004",
  USER_UNVERIFIED: "LG-1005",
};

const signupErrors = {
  INCOMPLETE_SIGNUP_CREDENTIALS: "RG-1000",
  INVALID_EMAIL_PATTERN: "RG-1001",
  INVALID_PHONE_NUMBER_PATTERN: "RG-1002",
  USER_WITH_EMAIL_ALREADY_EXISTS: "RG-1003",
  USER_WITH_PHONE_NUMBER_ALREADY_EXISTS: "RG-1004",
  USER_WITH_NIN_ALREADY_EXISTS: "RG-1005",
};

const otpErrors = {
  USER_ID_NOT_PROVIDED: "OTP-1000",
  OTP_NOT_PROVIDED: "OTP-1001",
  INVALID_OTP: "OTP-1002",
  OTP_BLACKLISTED: "OTP-1003",
  USER_ALREADY_ACTIVE: "OTP-1004",
};

const verificationErrors = {
  USER_DATA_MISMATCH: "VE-1000",
  DATABASE_VERIFICATION_ERROR: "VE-1001",
};

const authenticationErrors = {
  COOKIE_NOT_PROVIDED: "AE-1000",
  AUTHENTICATION_DATA_NOT_PROVIDED: "AE-1001",
};

const notFoundErrors = {
  USER_NOT_FOUND: "NF-1000",
};
module.exports = {
  loginErrors,
  signupErrors,
  otpErrors,
  verificationErrors,
  authenticationErrors,
  notFoundErrors,
};
